- name: Create Firefly III Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ firefly_data_directory }}/postgresql"
    - "{{ firefly_data_directory }}/mysql"
    - "{{ firefly_data_directory }}/upload"
    - "{{ firefly_data_directory }}/export"

- name: Firefly Cron
  template:
    src: firefly/cron
    dest: "{{ firefly_data_directory }}/cron"
    mode: '0755'

- name: Create MySQL container for Firefly
  docker_container:
    name: firefly-mysql
    image: mysql:5.7
    pull: true
    volumes:
      - "{{ firefly_data_directory }}/mysql:/var/lib/mysql:rw"
    env:
      MYSQL_DATABASE: "firefly"
      MYSQL_USER: "firefly"
      MYSQL_PASSWORD: "firefly"
      MYSQL_ROOT_PASSWORD: "firefly"
    restart_policy: unless-stopped
    memory: 1g

- name: Wait for MySQL to init
  pause:
    seconds: 30

- name: Create Firefly III container
  docker_container:
    name: firefly
    image: jc5x/firefly-iii:latest
    pull: true
    volumes:
      - "{{ firefly_data_directory }}/export:/var/www/firefly-iii/storage/export:rw"
      - "{{ firefly_data_directory }}/upload:/var/www/firefly-iii/storage/upload:rw"
      - "{{ firefly_data_directory }}/cron:/etc/cron.daily/firefly:rw"
    links:
      - firefly-mysql:db
    ports:
      - "{{ firefly_port }}:8080"
    env:
      APP_ENV: "local"
      APP_KEY: "{{ firefly_app_key }}"
      APP_URL: "firefly.{{ ansible_nas_domain }}"
      APP_FORCE_SSL: "true"
      DB_CONNECTION: "mysql"
      DB_HOST: "db"
      DB_DATABASE: "firefly"
      DB_USERNAME: "firefly"
      DB_PASSWORD: "firefly"
      TZ: "{{ ansible_nas_timezone }}"
      MAPBOX_API_KEY: "{{ firefly_map_api }}"
      USE_PROXIES: "127.0.0.1"
      TRUSTED_PROXIES: "**"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.backend: "firefly"
      traefik.frontend.rule: "Host:firefly.{{ ansible_nas_domain }}"
      traefik.enable: "true"
      traefik.port: "8080"
      traefik.frontend.whiteList.sourceRange: "{{ '' if firefly_available_externally=='true' else ansible_nas_localsubnet }}"
      traefik.frontend.whiteList.useXForwardedFor: "true"

      
